# Generated by Django 4.1.1 on 2022-09-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(unique=True, verbose_name="type code")),
                (
                    "name",
                    models.CharField(max_length=128, unique=True, verbose_name="name"),
                ),
                (
                    "standard_price",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="standard price"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="remarks"),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "project type",
                "verbose_name_plural": "project types",
            },
        ),
    ]
