# Generated by Django 4.1.1 on 2022-09-25 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("basedata", "0002_remove_projecttype_remarks_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileVendorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_inferred",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="inferred price"
                    ),
                ),
                (
                    "ratio_of_customer_price",
                    models.FloatField(
                        default=0.0, verbose_name="ratio of customer price"
                    ),
                ),
                (
                    "project_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="basedata.projecttype",
                        to_field="code",
                    ),
                ),
            ],
        ),
    ]
