# Generated by Django 4.1.1 on 2022-09-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basedata", "0003_profilevendorprofile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProfileVendorProfile",
            new_name="ProfileVendorPrice",
        ),
    ]
