# Generated by Django 4.1.1 on 2022-09-25 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vendor", "0008_remove_vendorprice_price_inferred_and_more"),
        ("basedata", "0004_rename_profilevendorprofile_profilevendorprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilevendorprice",
            name="vendor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="vendor.vendor",
            ),
            preserve_default=False,
        ),
    ]
